version: '3'

services:
  wp:
    build:
     context: ./
     dockerfile: Dockerfile
#    image: wordpress:php7.1 
    ports:
      - ${IP}:80:80 # change ip if required
    volumes:
      - ./wp-app:/var/www/html # Full wordpress project
      #- ./wp-app:/var/www/html:Z # Full wordpress project - RedHat / SELinux
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development remote_handler=dbgp   remote_enable=1 
    environment:
      XDEBUG_CONFIG: idekey=VSCODE remote_connect_back=1 default_enable=1
      # profiler_output_dir="/var/www/html 
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${DB_ROOT_PASSWORD}
      WORDPRESS_DEBUG: "true"
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', true);
#      XDEBUG_CONFIG: remote_host=localhost.localdomain
    depends_on:
      - db

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
      #- ./wp-data:/docker-entrypoint-initdb.d:Z  # RedHat / SELinux
      #- db_data:/var/lib/mysql:Z                 # RedHat / SELinux
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

volumes:
  db_data:

